### ISSUE TITLE
Feature request: add 1D plots

### ISSUE THREAD

**Issue by jni** [brisvag/napari-properties-plotter#4]
It should be possible to select a single feature for the x-axis, with the y-axis being used for a density plot. The individual points would be visible at the bottom of the plot.

**Comment by brisvag** [comment]
If you mean the ability plot things as a bar plot, with some arbitrary binning, it's in the plans!

Otherwise, could you elaborate? I don't understand this:

> individual points would be visible at the bottom of the plot.

**Comment by jni** [comment]
Yes, histograms/kdes. You can also show a density as individual points along an axis, kind of like seaborn.catplot with jitter=False. 

https://seaborn.pydata.org/tutorial/categorical.html

**Comment by brisvag** [comment]
Closed by #6 .
